# Generated by Django 5.2 on 2025-04-26 15:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="barcode",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
