# Generated by Django 5.2 on 2025-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_cast"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.TextField(blank=True, default=""),
        ),
    ]
