# Generated by Django 5.2 on 2025-04-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_genre"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="genre",
            new_name="genres",
        ),
    ]
