# Generated by Django 5.2 on 2025-04-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="price",
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
    ]
