# Generated by Django 5.2 on 2025-04-26 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatres", "0002_show_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="show",
            name="price",
        ),
    ]
