# Generated by Django 5.2 on 2025-04-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="home_address",
            field=models.CharField(default="N/A", max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=15),
        ),
    ]
